[build-system]
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]>=6.2",
    "pandas>=1.2",
    "numpy>=1.15",
    "rich>=11.0",
    "pyyaml>=5.3",
    "matplotlib>=3.3"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
